little_quiz/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('quizapp/', include('quizapp.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

polls/urls.py
from django.urls import path

from . import views


app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

quizapp/urls.py
from django.urls import path

from . import views


app_name = 'quizapp'

urlpatterns = [
    # ex: /quizapp/
    path('', views.index, name='index'),
    # ex: /quizapp/5/
    path('<int:quiz_id>/', views.quiz, name='quiz'),
    # ex: /quizapp/4/result/
    path('<int:quiz_id>/quiz_solution/', views.quiz_solution, name='quiz_solution'),
]

polls/models.py
from django.db import models
import datetime
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

quizapp/models.py
from django.db import models


class Category(models.Model):
    category_name = models.CharField(max_length=50)
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.category_name


class Quiz(models.Model):
    category = models.ManyToManyField(Category)
    pub_date = models.DateTimeField('date published')
    quiz_name = models.CharField(max_length=50)
    quiz_title = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    instructions = models.CharField(max_length=2000)

    def __str__(self):
        return self.quiz_name


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    question_name = models.CharField(max_length=50)
    question_text = models.CharField(max_length=200)

    def __str__(self):
        return "%s : %s" % (self.question_name, self.question_text)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_name = models.CharField(max_length=50)
    choice_text = models.CharField(max_length=200)
    is_correct = models.BooleanField()

    def __str__(self):
        return self.choice_name

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.views import generic

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    slug_url_kwarg = 'question'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'
    slug_url_kwarg = 'question'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

quizapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Quiz, Choice


def index(request):
    # show quizes
    latest_quiz_list = Quiz.objects.order_by('-pub_date')[:10]
    return render(request, 'quizapp/index.html', {'latest_quiz_list': latest_quiz_list})


def quiz(request, quiz_id):
    # show quiz
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    return render(request, 'quizapp/quiz.html', {'quiz': quiz})


def quiz_solution(request, quiz_id):
    # show the results of a quiz submission
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    correct_ct = wrong_ct = 0
    for question in quiz.question_set.all():
        q_choice_val = request.POST[question.question_name][0]
        choice_truth = get_object_or_404(Choice, pk=q_choice_val)
        if choice_truth.is_correct:
            correct_ct += 1
        else:
            wrong_ct += 1

    response_body = '# Total : %s<br># Correct : %d<br># Wrong : %d'
    return HttpResponse(response_body % (correct_ct + wrong_ct, correct_ct, wrong_ct))

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href= "{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

quizapp/templates/quizapp/index.html
{% if latest_quiz_list %}
    <ul>
    {% for quiz in latest_quiz_list %}
        <li><a href="{% url 'quizapp:quiz' quiz.id %}">{{ quiz.quiz_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No quizzes are available.</p>
{% endif %}

quizapp/templates/quizapp/quiz.html
{% load static %}

<h1>{{ quiz.quiz_title }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'quizapp:quiz_solution' quiz.id %}" method="post">
{% csrf_token %}
{% for question in quiz.question_set.all %}
    <img src="{% static 'quizapp/images/728x90-Placeholder.gif' %}">
    <fieldset>
        <legend>{{ question.question_text }}</legend><br>
        {% for choice in question.choice_set.all %}
            <input type="radio" name="{{ question.question_name }}" id="{{ question.question_name }}{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="{{ question.question_name }}{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset><br><br>
{% endfor %}
<input type="submit" value="Submit">
</form>